### ISSUE TITLE
Ext.log undefined for sencha touch 2.0

### ISSUE THREAD

**Issue by jachenry** [deftjs/DeftJS#2]
I get the following error when trying to include deft.js in a sencha touch 2.0 project.

`Uncaught TypeError: Property 'log' of object #<Object> is not a function`

**Comment by johnyanarella** [comment]
Thanks for reporting this issue.

Ext JS 4.0 expects Ext.log() and Sencha Touch 2.0 expects Ext.Logger.log().

Ext.Logger is actually an alias for Ext.log.Logger - there's an entire package of classes located at the Ext.log namespace in Sencha Touch, rather than a single function as in Ext JS.

To abstract away this complexity and better protect our implementation from inevitable changes on the Ext JS side in future releases, we will likely need to create our own Logger class, detect the running environment and set the proper function aliases at runtime.
