### ISSUE TITLE
How to get a reference to the app instance?

### ISSUE THREAD

**Issue by neilmcguigan** [deftjs/DeftJS#21]
In Sencha's controllers, the application is passed in, and set to controller.application. 

How do I get a reference to the application from a Deft ViewController? Or do I not want to do that? 

How do I fire an app-wide event?

Thanks

Neil

**Comment by johnyanarella** [comment]
The answer depends on whether you are planning on using any of the other capabilities of `Ext.app.Application`.  If you are using the Deft JS IoC container for dependency injection (instead of using the `stores`, `views`, `models` configs in `Ext.app.Application`) and Deft JS View Controllers (instead of `Ext.app.Controller` and the `controllers` config in `Ext.app.Application`), chances are you don't not need `Ext.app.Application` anymore.  

If you want an application-wide event bus, you can configure the IoC container with one and inject it as needed.  To do so, you simply configure the IoC container with an instance of `Ext.util.Observable` to be injected wherever needed.

``` javascript
Deft.Injector.configure({
    eventBus: 'Ext.util.Observable'
});
```

(This works because in addition to being usable as a mixin, `Ext.util.Observable` can also be directly instantiated and used as a standalone event bus.)

If it turns out you still need `Ext.app.Application`, you can configure the IoC container with the `Ext.app.Application` instance as the `value`, like so:

``` javascript
Ext.application({
    name: 'MyApp',
    launch: function() {
        Deft.Injector.configure({
            'application': {
                value: this
            }
        });

        // Create Viewport and views
        ...
    }
});
```

I created an example of this approach on JSFiddle here: http://jsfiddle.net/CodeCatalyst/K2ZgR/

`Deft.Injector.configure()` can be called multiple times in your application.  Each time it is called it adds or updates the specified identifiers.  In this case, you'll want to do the majority of your IoC container configuration in `Ext.onReady()` and only configure the application reference within your `Ext.app.Application`'s `launch()` method.  

Be careful, though. If you use `Ext.app.Application`'s `stores` or `controllers` configs, the singleton instances it creates are instantiated _before_ the `Ext.app.Application` instance's constructor or `launch()` method are fired.  If you've instantiated classes that depend on the `application` before then, `Deft.Injector` will throw an error because the `application` identifier can only be resolved after its been created and you've configured the IoC container with that reference.

**Comment by neilmcguigan** [comment]
That's awesome John. Thank you a ton.

Deft is a much better solution than Sencha's first attempt at MVC.

Cheers,

Neil

On Tue, Jun 12, 2012 at 8:42 AM, John Yanarella <
reply@reply.github.com
