### ISSUE TITLE
DeftJS views dont work with Sencha Architect

### ISSUE THREAD

**Issue by tsteele** [deftjs/DeftJS#24]
to create a view with Sencha Architect and use the controllable mixin, Within Archiect I have created an override to include the mixin:

Ext.define('article.view.override.Preview', {
    requires: 'article.view.Preview',
    mixins: [ 'Deft.mixin.Controllable', 'Deft.mixin.Injectable' ] 
}, function() {
    Ext.override(article.view.Preview,  {  
    });
});

The mixin
 targetClass.prototype.constructor = Ext.Function.createSequence(targetClass.prototype.constructor, function() {....
code is reached, but the body never gets executed, and the controller is not created.

if I move the mixins: [ 'Deft.mixin.Controllable', 'Deft.mixin.Injectable' ]  into the article.view.Preview class it works .

**Comment by johnyanarella** [comment]
Very clever idea.

This may be tricky to pull off because Controllable (and soon Injectable) leverage the Sencha Class system's class preprocessor features.  Consequently, there is logic triggered and executed within the original Ext.define() for the class that won't be applied if those annotations are added afterward.

I'll have to carve out some time soon to investigate your proposed approach and see if there's anything we can do to facilitate integration with Sencha Architect.  Thanks for sharing!

As we get closer to reaching our 1.0 milestone we'll be reaching out to Sencha to see about coordinating to add official support.

**Comment by johnyanarella** [comment]
Deft JS v0.8 will deprecate the `Deft.mixin.Controllable` and `Deft.mixin.Injectable` mix-ins.  You will still specify `inject` and `controller` class annotations, but the mix-ins are omitted and the annotations are processed via Sencha class preprocessors instead.
