### ISSUE TITLE
"Live" control event listeners do not work with nested controls

### ISSUE THREAD

**Issue by ghost** [deftjs/DeftJS#70]
With "live" controls, DeftJS can add listeners to direct children controls, but it does not add listeners to nested controls correctly.

Imagine that I have a edit form that needs to create dynamically. I want to handle "tap" event of several editing buttons which are nested in some panels, so I have created "live" controls in controller. I can see in console log that DeftJS added "tap" listeners to those controls but handlers are not fired when I tap them.

**Comment by brian428** [comment]
John already has a multiple Jasmine tests to verify the live selector behavior (starting here https://github.com/deftjs/DeftJS/blob/master/spec/coffee/Deft/mvc/ViewController.coffee#L863), so we'd probably need a reproducible test sent over that demonstrates the issue. If you like, post to the mailing list (https://github.com/deftjs/DeftJS/wiki/Resources-and-Mailing-List) and attach a simple example of what you're doing so that I and others can try to assist.
