### ISSUE TITLE
view controller doesn't bind scope to itself, when using a selector query

### ISSUE THREAD

**Issue by dab0uncer** [deftjs/DeftJS#9]
I made this control object:

``` javascript
      control: {
         myButton: {
            selector : 'button[text="click me!"]',
            listeners: {
               click: 'onButtonClick'
            }
         }
      }
```

but in onButtonClick() "this" is the button and not the controller, like stated in the documentation.

**Comment by johnyanarella** [comment]
Is this an Ext JS or Sencha Touch app?  With which version and in which browser?

I am unable to replicate this issue with Ext JS 4.1.  For me, the onButtonClick() is being executed in the view controller's scope.  

See this jsfiddle (with Safari or Chrome developer tools enabled) for my attempt to replicate your issue: http://jsfiddle.net/3CPdR/3/

I was surprised to see this one because we explicitly cover this in our unit tests, and those are passing for Ext JS 4+ and Sencha Touch 2+.

**Comment by dab0uncer** [comment]
I thought the "getMyButton()" function was from the button class, because I didn't name the button "myButton" so I assumed there wouldn't be a autmatically generated function called like this in the controller...

Ok then the problem lies elsewhere, thank you :)

**Comment by johnyanarella** [comment]
No problem!  Thanks for posting your concern here, feel free to do so again in the future.
